"""rename a common table phone_advert

Revision ID: b4931a6ea877
Revises: 7509008baf35
Create Date: 2023-05-10 15:57:51.874315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4931a6ea877'
down_revision = '7509008baf35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_advert',
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advert_id'], ['advert.advert_id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.phone_id'], ),
    sa.PrimaryKeyConstraint('advert_id', 'phone_id')
    )
    op.drop_table('association_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('advert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['advert_id'], ['advert.advert_id'], name='association_table_advert_id_fkey'),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.phone_id'], name='association_table_phone_id_fkey'),
    sa.PrimaryKeyConstraint('advert_id', 'phone_id', name='association_table_pkey')
    )
    op.drop_table('phone_advert')
    # ### end Alembic commands ###
