"""add updated_at field

Revision ID: dc31c9311234
Revises: 
Create Date: 2023-03-20 20:48:43.327285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc31c9311234'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advert', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('advert', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    op.add_column('brand', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('brand', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    op.add_column('model', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('model', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    op.drop_column('model', 'updated_at')
    op.alter_column('brand', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    op.drop_column('brand', 'updated_at')
    op.alter_column('advert', 'saved_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"))
    op.drop_column('advert', 'updated_at')
    # ### end Alembic commands ###
